version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install
                      cd symbols-mui && yarn install:dependencies
            - run:
                  name: Build Packages
                  command: |
                      yarn build
                      cd symbols-mui && yarn build
            - run:
                  name: Verify SVG Build Artifacts
                  command: |
                      yarn test:svg
                      cd symbols-mui && yarn test
            - persist_to_workspace:
                  root: .
                  paths:
                    - symbols

    publish:
      docker:
        - image: circleci/node:12.9.1-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command:  |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @pxblue/symbols
            command: cd symbols && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/symbols-mui
            command: cd symbols-mui && yarn publish:package -b $CIRCLE_BRANCH
workflows:
  version: 2
  symbols:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
