version: 2
jobs:
    build:
        docker:
            - image: circleci/node:12.6-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install
            - save_cache:
                  paths:
                      - node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}
            - run:
                  name: Build Packages
                  command: yarn build
            - run:
                  name: Verify SVG Build Artifacts
                  command: yarn test:svg
            - persist_to_workspace:
                  root: .
                  paths:
                    - symbols

    publish:
      docker:
        - image: circleci/node:12.9.1-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command:  |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @pxblue/icons
            command: yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/symbols
            command: cd symbols &&  yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/icons-svg
            command: cd svg && yarn publish:package -b $CIRCLE_BRANCH
workflows:
  version: 2
  icons:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
